### ISSUE TITLE
java.lang.ClassNotFoundException: Unable to load class: com.microsoft.sqlserver.jdbc.SQLServerDriver on new docker container

### ISSUE THREAD

**Issue by levalencia** [camunda/docker-camunda-bpm-platform#101]
The scenario I am trying to achieve is to have camunda running on a docker container, but the database should be Azure MS SQL, Not mysql, not postgress as MSSQL is our preferred DB.

I already tested it with h2 and mysql and it works fine

However I am not able to install the JDBC Drivers correctly.

I used your docker file, but I changed a few things

```
#MSSQL SERVER JDBC DRIVER INSTALL
COPY sqljdbc_7.2.2.0_enu.tar.gz /tmp/
WORKDIR /tmp
RUN tar -xf sqljdbc_7.2.2.0_enu.tar.gz
ENV CLASSPATH ${CLASSPATH}:/tmp/sqljdbc_7.2/enu/mssql-jdbc-7.2.2.jre11.jar
ARG CLASSPATH=${CLASSPATH}:/tmp/sqljdbc_7.2/enu/mssql-jdbc-7.2.2.jre11.jar
RUN echo $CLASSPATH

ENV CAMUNDA_VERSION=${VERSION}
ENV DB_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
ENV DB_URL=jdbc:sqlserver://xx.database.windows.net:1433;database=xx;user=demo@architectureplaygroundcamunda;password=xx.;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
ENV DB_USERNAME=xx@architectureplaygroundcamunda
ENV DB_PASSWORD=x
```

However I have this error:
https://stackoverflow.com/questions/57850669/java-lang-classnotfoundexception-unable-to-load-class-com-microsoft-sqlserver

Can you help me a bit with this?

**Comment by AndreaGiardini** [comment]
Hello @levalencia 

Since MSSQL is not supported by our Docker image I wouldn't consider this as an "issue", but rather a support request. You have better chances of getting an answer by posting in our forum ( https://forum.camunda.org/ ) where other members of the community might be able to help you :)

**Comment by levalencia** [comment]
is not supported by the docker image, but is it supported by camunda?

**Comment by levalencia** [comment]
thanks, I posted the question there too, been looking for some help for the last days with this and cant find any documentation about it.

**Comment by AndreaGiardini** [comment]
That's correct, you can find the list of supported databases (for 7.11) here: https://docs.camunda.org/manual/7.11/introduction/supported-environments/#supported-database-products

We are not including every driver in the Docker image, but just the most popular ones :)

**Comment by levalencia** [comment]
Just a last question, what is the tomcat path  where I need to put jar files? I just cant seem to find this.

**Comment by AndreaGiardini** [comment]
I think copying the jar files in the `/camunda/lib` folder should work :)

**Comment by adrianriepl** [comment]
I can't quite get it to work with MSSQL.

I created a new Dockerfile based on the image in the docker hub:

```
FROM camunda/camunda-bpm-platform:latest
# Install MSSQL Server JDBC Driver
ADD mssql-jdbc-7.2.2.jre8.jar /camunda/lib/
```

After I built the new image (Image ID:  5d10be13b2ab) from the Dockerfile, I tried to run a container of it:

`docker run --env-file db-env.txt --name camunda -p 8080:8080 5d10be13b2ab`

**Configuration of database in `db-env.txt`:**

```
DB_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
DB_URL=jdbc:sqlserver://localhost:1433;databaseName=WorkflowEngine;
DB_USERNAME=camunda
DB_PASSWORD=camunda
```

But then while the container starts up I get the following error:

`com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 1433 has failed. Error: "Connection refused (Connection refused). Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".`

I also have checked if TCP is enabled on the SQL Server and configured:

![image](https://user-images.githubusercontent.com/11076678/65951638-c1aea980-e440-11e9-8620-589cd902d879.png)

![image](https://user-images.githubusercontent.com/11076678/65951664-cf642f00-e440-11e9-9b6f-f00cf21e4c69.png)

Is my configuration wrong?

**Comment by AndreaGiardini** [comment]
Not an expert on windows / SQLServer so please take my reasoning as a wild guess...

The absence of driver-related error messages makes me think that it's probably a network problem rather than a docker-image problem.
I am assuming that you are running the camunda docker container on the same windows machine that is running the MSSQL server right? in this case `localhost:1433` does not work since it's pointing to `localhost` inside the container.

You have two options at this point:
- Running the container with `net=host`
- Run MSSQL server in a docker container as well and share their network

Let me know how it goes. Feel free to open a new thread on forum.camunda.com if it's not fixed, you will probably get better support over there :)

**Comment by adrianriepl** [comment]
You are right when I use `localhost` it's pointing to the `localhost` inside of the container. As I do not want to run MSSQL Server in a separate container I tried using `--net=host` but this didn't work either.

In combination with your tip and this [tutorial](http://kienct.com/2018-05-03-connecting-to-local-sql-server-from-container/), I managed to do it. **I now use `host.docker.internal` instead of `localhost`.**

So my configuration file `db-env.txt` looks the following:

```
DB_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
DB_URL=jdbc:sqlserver://host.docker.internal:1433;databaseName=WorkflowEngine;
DB_USERNAME=camunda
DB_PASSWORD=camunda
```
Now everything works. Thank you very much for your help :smile:
