### ISSUE TITLE
enable engine-rest authentication

### ISSUE THREAD

**Issue by nesies** [camunda/docker-camunda-bpm-platform#119]
By default, the engine-rest API has no authentifcation. Which is no so great when deploying (production or not).

According to https://docs.camunda.org/manual/7.12/reference/rest/overview/authentication, engine-rest/WEB-INF/web.xml contains a XML blocs which can be uncommented

**Comment by lwille** [comment]
as mentioned on #120, there is currently no easy way to configure the `engine-rest` component.

To make this work in a maintainable and compatible way, one should consider either generating the `web.xml` from a template or injecting the required snippet (similar to the one that @nesies uncommented in #120).

The difference between uncommenting something and injecting it is not marginal: a commented-out block might just be removed (because that's what you do with inactive code) and this might break the feature, whereas an injected snippet will do exactly what it's supposed to do.

We understand that this is an important feature for the community and will do our best to support you :-)

**Comment by nesies** [comment]
Ok, i will rework my pull to inject instead of uncommenting.

Anyway, an automatic test (in Travis?) might be pertinent to ensure engine-rests AUTH is really enabled :)

**Comment by lwille** [comment]
After many discussions and multiple implementation attempts, I'd suggest to close this issue.
 
Configuring the REST authentication is quite specific to the distributution being used, and the docker images we're maintaining here aim to be as universal as possible.

Unless you're ok with maintaing your own image on top of the "offical" ones (can be done nicely with dockerHub automatic builds),  consider mounting a custom web.xml for your `tomcat` distribution.

Alternatively, check out the new [`camunda-run`](docker pull camunda/camunda-bpm-platform:run) distribution, which is based on Spring Boot and brings a more modern configuration approach (it's still in alpha, but the next release is already on the horizon).
