### ISSUE TITLE
Silence Nashorn deprecation warnings

### ISSUE THREAD

**Issue by tomlarkworthy** [camunda/docker-camunda-bpm-platform#129]
Logs are filled with "Warning: Nashorn engine is planned to be removed from a future JDK release" for JDK 11.00

https://stackoverflow.com/questions/55641738/how-to-hide-java-11-nashorn-deprecation-warnings

**Comment by AndreaGiardini** [comment]
Hello @tomlarkworthy and thank you for raising this issue :)

I had a chat with some Camunda BPM developers. This warning is triggered whenever javascript is executed. In general, we don't recommend using javascript as a scripting language with Camunda.
You can disable that warning with the `--no-deprecation-warning` flag if your logs are growing too much.

Let me know if you have other questions. I will close the issue since this is not a problem with Camunda BPM or the docker image :)

**Comment by tomlarkworthy** [comment]
That's a Nashorn compiler flag that needs to be set when instantiating the
scripting engine. I cannot set it, it would need to be done inside Camunda.

**Comment by AndreaGiardini** [comment]
In this case, it makes sense to create an issue in the camunda-bpm-platform project since it's still not related to the docker container. You can open an issue at the following link: https://app.camunda.com/jira

**Comment by tomlarkworthy** [comment]
done thanks for the pointer (https://jira.camunda.com/browse/CAM-11687)

**Comment by ThorbenLindhauer** [comment]
FYI the warnings can be switched off by providing the following JVM argument: ` -Dnashorn.args="--no-deprecation-warning"`. I'm afraid it is not easy to fix this in Java code as explained in https://jira.camunda.com/browse/CAM-11687. 

@AndreaGiardini it could make sense to apply the JVM argument out of the box for our Docker containers. What do you think?
