### ISSUE TITLE
Tweak `JAVA_OPTS` to use JDK 11 container support

### ISSUE THREAD

**Issue by ceefour** [camunda/docker-camunda-bpm-platform#137]
Currently this line hardcodes the RAM requirements:

https://github.com/camunda/docker-camunda-bpm-platform/blob/1f78b498716a34659e1c3d3af82e4fe52b700013/Dockerfile#L52

As the Docker image now runs on OpenJDK 11 (currently on `alpine`, I'm advocating for `ubuntu` that's another topic #138), which means there is [container support](https://github.com/AdoptOpenJDK/openjdk-docker/issues/126#issuecomment-480155536). See: https://medium.com/@jnsrikanth/docker-support-in-java-10-fbff28a31827

So I'm proposing to either remove `JAVA_OPTS` default setting or tweak it so that it's relative to Docker container limits. Especially in Kubernetes that we have and can use `requests/limits`, Docker containers should just adhere to the limits set.

**Comment by koevskinikola** [comment]
Hi @ceefour,

Thank you for raising this topic. Since we will soon disable GitHub issues in this repository, I created [CAM-14495](https://jira.camunda.com/browse/CAM-14495) for this topic. You can follow it for updates.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
