### ISSUE TITLE
View deployment Issue

### ISSUE THREAD

**Issue by siva1097** [camunda/docker-camunda-bpm-platform#143]
Unable to view deployments in camunda cockpit in 7.14.0. I tried to view the deployments in 7.13.0, It seems to work fine.  
![Camunda_Deployment_7 14 0](https://user-images.githubusercontent.com/35173171/84906682-e4b4e280-b0cf-11ea-9fad-18b353c56a01.png)
![Camunda_Home_7 14 0](https://user-images.githubusercontent.com/35173171/84906696-e7173c80-b0cf-11ea-8a2e-598188403ad6.png)
![Camunda_Deployment_7 13 0](https://user-images.githubusercontent.com/35173171/84906746-f8604900-b0cf-11ea-8b2d-6e1f4f6d1d54.PNG)

Thanks.

**Comment by AndreaGiardini** [comment]
Hello @siva1097 

This looks to me like a configuration problem or a bug, but it is probably not related to our Docker image. Please head over to the forum for community support ( https://forum.camunda.org/ ) or open a bug report in our main repository https://github.com/camunda/camunda-bpm-platform/

I'm going to close this issue since the reported problem is unrelated with docker
