### ISSUE TITLE
Provide onbuild images

### ISSUE THREAD

**Issue by menski** [camunda/docker-camunda-bpm-platform#15]
onbuild images can be used to add additional libraries and webapps without knowing the file hierarchy of the container

**Comment by koevskinikola** [comment]
Into on `ONBUILD` instruction: https://dockerlabs.collabnix.com/beginners/using-onbuild-images/

**Comment by koevskinikola** [comment]
We will soon disable the GitHub issues on this repository. As there doesn't seem to be a lot of interest in this topic since it was created, and we don't have time to implement it, I am closing this issue.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for feature requests or bug reports.

Best,
Nikola
