### ISSUE TITLE
DEBUG port binds only to localhost in Wildfly14 and cannot be accessed from outside the container

### ISSUE THREAD

**Issue by ratskinmahoney** [camunda/docker-camunda-bpm-platform#191]
Hi,

Encountered this issue using the wildfly-7.15.0 container, but based on inspection it appears that the issue is still present in 7.16.0. It does not appear to apply to the tomcat version so far as I can tell.

Specifying `DEBUG=true` will result in the debug port being opened on 8000, however, since Java 11 this binds only to localhost by default and hence is not available outside of the container (e.g. https://stackoverflow.com/a/53295262).

We've addressed this locally by modifying the `camunda.sh` from:

```
if [ "${DEBUG}" = "true" ]; then
  echo "Enabling debug mode, JPDA accesible under port 8000"
  CMD+=" --debug 8000"
fi
```

to: 

```
if [ "${DEBUG}" = "true" ]; then
  echo "Enabling debug mode, JPDA accesible under port 8000"
  CMD+=" --debug *:8000"
fi
```

**Comment by ratskinmahoney** [comment]
PR #192 raised.

**Comment by koevskinikola** [comment]
Hi @ratskinmahoney,

Thank you for reporting this. I created [CAM-14470](https://jira.camunda.com/browse/CAM-14470) to track the progress of this issue since we will soon disable the GitHub issues on this repository.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
