### ISSUE TITLE
Is there an easy way to enable authentication with docker image?

### ISSUE THREAD

**Issue by Mrchensama** [camunda/docker-camunda-bpm-platform#194]
As mentioned in the title, i'm now trying to find out a easy way to enable authenticaition with docker image. I've searched a lot but without any related answers.

**Comment by Mrchensama** [comment]
Appreciation to any reply. :)

**Comment by koevskinikola** [comment]
Hi @Mrchensama,

It's not really clear from the description, what type ot authentication you are trying to add.

Since we will soon disable the GitHub issues on this repository, I am closing this issue. Please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) to describe your feature request there.

For help requests, please open a help request topic on the [Camunda forum](https://forum.camunda.org/) or [a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.


Best,
Nikola
