### ISSUE TITLE
Whitelabel Error Page when using Docker

### ISSUE THREAD

**Issue by rafaelreuber** [camunda/docker-camunda-bpm-platform#210]
I'm getting an error when a I try to open comunda web application. I'm using docker.
The error message that browser shows is: "This application has no explicit mapping for /error, so you are seeing this as a fallback."

### Step to reproduce:
1) Start the camunda container

```bash
docker pull camunda/camunda-bpm-platform:latest
docker run -d --name camunda -p 8080:8080 camunda/camunda-bpm-platform:latest
```

2) Open the browser using the url http://localhost:8080/camunda-welcome/index.html
2.1) The browser shows the error:
## Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Dec 07 09:44:57 UTC 2021
There was an unexpected error (type=Not Found, status=404).

**Comment by koevskinikola** [comment]
Hi @rafaelreuber,

I suspect that you are using Camunda Run. The error message you saw was shown because the `camunda-welcome` page was not available in Camunda Run. The issue was resolved with [CAM-11911](https://jira.camunda.com/browse/CAM-11911), so you shouldn't see it from Camunda Platform 7.17.0 onwards.

If you do see a similar error, please open a [JIRA CAM issue](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues), as we will soon close the issue tracker on this repository.

Best,
Nikola
