### ISSUE TITLE
Align database driver names in jboss and wildfly with tomcat ones

### ISSUE THREAD

**Issue by menski** [camunda/docker-camunda-bpm-platform#25]
Often the user misses the note that the drivers have different names in jboss and wildfly.

**Comment by ppk0907** [comment]
Haha I spent some time trying to figure this out too. Aligning the driver names would be nice, but I personally think that just phrasing it little differently might be something easy to do and could reduce the confusion. Maybe something along the line of this - "For Jboss and Wildfly distributions, instead of using the namespace(or whatever that is called), please use one of the following database identifiers for DB_DRIVER: **h2**, **mysql** or **postgresql**."

**Comment by menski** [comment]
Thanks for the feedback. I will adjust the phrasing if this makes it more clear.

**Comment by menski** [comment]
Was done with the latest refactoring
