### ISSUE TITLE
Should the image define docker aware flags?

### ISSUE THREAD

**Issue by lightswitch05** [camunda/docker-camunda-bpm-platform#39]
[Java SE 8u131](https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits) added a new flag to become aware of docker imposed memory limits.

We've had issues with this image running out of memory. We fixed it by directly setting heap limits using `-Xmx`. However, Java SE has a new flag to discover docker imposed memory limits on its own: `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap`. I believe this could be added in a backwards compatible way since it only uses cgroup memory limits if `-Xmx` is not already defined. I have not researched if the camunda application is already setting `-Xmx` elsewhere

**Comment by menski** [comment]
Hi @lightswitch05,

thanks for raising this issue. I wanted to look into this new option but forgot about it. I will give it a try but for example the tomcat already starts with `-Xmx512m` per default, so from your explanation I guess the new flag would have no effect? But maybe its better to override that and allow the user to either control the memory with the docker settings or a env variable, instead of relying on the default.

**Comment by lightswitch05** [comment]
@menski yes controlling it with a docker setting/env var would be the "docker" way. It might not be able to be done in a backwards compatible way

**Comment by menski** [comment]
With #73 it is now possible and documented to override the default memory settings. I decided against changing the default to use docker memory settings as this would not be backwards compatible. So containers without a memory limit would immediately consume a lot more memory.
