### ISSUE TITLE
Pushing new images for old versions

### ISSUE THREAD

**Issue by mpoindexter** [camunda/docker-camunda-bpm-platform#55]
Less a bug, and more a request for future changes:

Looks like today there was a new version of the camunda/camunda-bpm-platform:tomcat-7.8.0 image pushed.  This is a very different image than the previous version that appeared at this tag.  In particular, it changed the name of the startup script, changed the user that the service runs under, and changed the base distribution.  This all is pretty incompatible for anyone who built a docker image that extended the old one (i.e. `FROM camunda/camunda-bpm-platform:tomcat-7.8.0` -> customize image).

In the future would it be possible not to make such incompatible changes to previously published releases?

**Comment by menski** [comment]
Hi @mpoindexter,

thanks for reaching out. You can find more information in this post https://forum.camunda.org/t/new-community-docker-images/7470/1 about the new images. I'm aware that overridden the old images was not the best solution but I preferred to have consistent images on all versions instead of a cut at 7.9.0.

In case you still want to build the old images locally you can find them on the `archive` branch, i.e. for tomcat https://github.com/camunda/docker-camunda-bpm-platform/tree/archive/7.8.0/tomcat. Please be aware that there was an issue with the latest ubuntu image (https://github.com/camunda/docker-camunda-bpm-platform/issues/53). You either have to change the FROM to ubuntu:16.04 or adjust the changes described in the issue.

Sorry for the inconvenience but I hope this will not happen again. The old images where just outdated and had to be reworked.

Cheers,
Sebastian

**Comment by michaelarnauts** [comment]
Wow, this screwed our setup. Since the user changed, the permissions for the database were incorrect. This caused this container to halt during startup.

I agree with the @mpoindexter that it's not done to change existing images that breaks current systems.
