### ISSUE TITLE
Deployment aware job execution might not be a good default

### ISSUE THREAD

**Issue by benhoffmann** [camunda/docker-camunda-bpm-platform#75]
Because of that option, the job executor will not acquire new jobs after restarting the container for models that have been deployed using the REST API.  Especially for Docker, people are more likely to deploy models using REST than deploying a war file into their container.

This will make instances look like they got stuck after restarting the container and make people wonder what's wrong. I've seen this a couple of times with clients and prospects on site and I think this doesn't provide the best getting started experience.

One solution would be to change the default for the docker "distro". The other option would be to prominently highlight this fact somewhere in the documentation. Still, in that case people have to deal with the mechanics of the job executor when they are just about to try out Camunda.

**Comment by menski** [comment]
That is a good point. What I think is easy to achieve is to provide an environment variable to allow users to configure this aspect. I probably will not change the default for older release but for 7.11 we could think about switching this to default `false`. Other than that maybe the Camunda core will change it's behavior to better handle the different deployments. Feel free to provide a PR for this feature or I will look into it when I find time.

**Comment by falko** [comment]
related to: https://app.camunda.com/jira/browse/CAM-10062

**Comment by Minisha** [comment]
@menski  so possible to inject false via env variable now?

**Comment by koevskinikola** [comment]
Hi everyone,

In the Camunda Platform Run distribution, the `jobExecutorDeploymentAware` is set to false. Furthermore, exposing environment variables for different configuration options in Camunda Platform 7 would be difficult to maintain since we provide different distributions (Tomcat, Wildfly, Run), which load configuration files in a different way.

We recommend using Docker to mount the appropriate Camunda Platform configuration file into the image. I created https://jira.camunda.com/browse/CAM-14452 to improve the README to make it easier for users of our Docker images to find out how to configure Camunda Platform 7.

Note: We will soon disable the GitHub issues on this repository. This is why I am closing this issue.

For help requests, please open a help request topic on the [Camunda forum](https://forum.camunda.org/) or [a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
