### ISSUE TITLE
FreeMarker Script Engine not found in wildfly docker image

### ISSUE THREAD

**Issue by Alex-Ph** [camunda/docker-camunda-bpm-platform#90]
_Steps to reproduce:_

- I downloaded and started camunda/camunda-bpm-platform:wildfly-7.12.0-SNAPSHOT like described [here](https://hub.docker.com/r/camunda/camunda-bpm-platform). 

- After that I deployed and started this bpmn which starts a script task to list all installed script engines:[list_all_found_scripts_bpm.zip](https://github.com/camunda/docker-camunda-bpm-platform/files/3305614/list_all_found_scripts_bpm.zip)

- Check the log files

_Issue:_
The script does not list FreeMarker:

```
04:58:29,212 INFO [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 16.0.0.Final (WildFly Core 8.0.0.Final) started in 13035ms - Started 755 of 949 services (350 services are lazy, passive or on-demand)
04:59:58,881 INFO [stdout] (default task-1) Oracle Nashorn
04:59:58,882 INFO [stdout] (default task-1) 1.8.0_212
04:59:58,883 INFO [stdout] (default task-1) ECMAScript
04:59:58,885 INFO [stdout] (default task-1) ECMA - 262 Edition 5.1
04:59:58,886 INFO [stdout] (default task-1) [js]
04:59:58,887 INFO [stdout] (default task-1) [application/javascript, application/ecmascript, text/javascript, text/ecmascript]
04:59:58,888 INFO [stdout] (default task-1) [nashorn, Nashorn, js, JS, JavaScript, javascript, ECMAScript, ecmascript]
```

If I do the same steps with the tomcat docker image, it lists also freemarker as engine. I double checked the module folders like described in the documentation. Also, I am able to use groovy and freemarker as Script type and define variables like ${testVar}, but I am not able to use FreeMarker inline in a javascript (like in the provided script task).

Issue is created based on this forum topic: https://forum.camunda.org/t/freemarker-script-engine-not-found-in-wildfly-docker-image/13465

**Comment by koevskinikola** [comment]
Hi @Alex-Ph,

I am closing this issue since we will soon disable the GitHub issues on this repository. So I would like to ask you to create a ticket in our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues).

It would be useful if you could provide an example project or BPMN process where you show the bug. What you currently provided shows us that Freemarker isn't listed as a script engine, but as you mentioned, it can still be used in a Script Task.

Best,
Nikola

Best,
Nikola
