### ISSUE TITLE
Error when Tomcat-based Docker container is restarted

### ISSUE THREAD

**Issue by agavrilov** [camunda/docker-camunda-bpm-platform#99]
I'm using camunda/camunda-bpm-platform:tomcat-7.11.0 Docker image. The first time the container starts normally. But when container is restarted, I get the following message:

```
Configure database
/camunda/conf/server.xml:47.492: Attribute testOnBorrow redefined
alse" validationQuery="SELECT 1" testOnBorrow="false" validationQuery="SELECT 1"
^
/camunda/conf/server.xml:47.492: Attribute validationQuery redefined
alse" validationQuery="SELECT 1" testOnBorrow="false" validationQuery="SELECT 1"
```

See also https://forum.camunda.org/t/breaking-change-in-latest-docker-images/14316

**Comment by AndreaGiardini** [comment]
Hello @agavrilov 

I just backported a fix for the image. There was a bug that passed our review phase and it was not found by tests. This situation happens when the container is restarted more than once and the `testOnBorrow` attribute gets added twice, making the tomcat configuration invalid.

Can you re-try after pulling the image again?

**Comment by agavrilov** [comment]
It works now. Thanks!

**Comment by chetanku** [comment]
Hey @AndreaGiardini , I still see this issue in the **camunda-bpm-platform-ee:7.11.2** version, I tried setting testonborrow both ways(true and false), but I still see this issue when the container is restarted. Can you point me to the right image version? Let me know if you need more information.

**Comment by AndreaGiardini** [comment]
@chetanku The fix was backported to `camunda-bpm-platform-ee:7.11.3` :)

**Comment by chetanku** [comment]
Thanks @AndreaGiardini. it works now :)
